
ALTER TABLE TilskudForhoejetTakst CONVERT TO CHARACTER SET UTF8;
ALTER TABLE Tilskudsblanket CONVERT TO CHARACTER SET UTF8;
ALTER TABLE TilskudsblanketTerminal CONVERT TO CHARACTER SET UTF8;
ALTER TABLE TilskudsblanketKroniker CONVERT TO CHARACTER SET UTF8;
ALTER TABLE TilskudsblanketForhoejet CONVERT TO CHARACTER SET UTF8;
ALTER TABLE TilskudsblanketEnkelt CONVERT TO CHARACTER SET UTF8;
